### PR TITLE
Make `GetHavocStackPow2<Tag>` correctly used in AFLHavocOptimizer

### PR DESCRIPTION
**Pull request by potetisensei**
## Type of PR

- [ ] Changes related to the roadmap (e.g., TODO.md) (type: A) -> Create an issue corresponding to the PR in advance, and refer to this PR in the issue.
- Changes that are not related to the roadmap
    - [ ] Change with multiple possible solutions to the issue (type: B-1) -> Create an issue corresponding to the PR in advance and refer to this PR in the issue.
    - [x] Change with a single solution (type: B-2) -> There is no need to create an issue corresponding to the PR in advance. Please discuss it in this PR.

## Importance of PR

- Importance of the issue
    - [ ] Large (based on several days to weeks of discussion and verification, e.g., this issue is a blocking issue for other issues on the roadmap, etc.)
    - [x] Medium (based on a few hours to a day of discussion and verification, e.g., this issue is a blocking issue for another minor issue)
    - [ ] Small (apparent changes such as build error)
- Complexity of the solution (code, tests, etc.)
    - [ ] Large (requires several days to several weeks of review)
    - [ ] Medium (requires several hours to a day of review)
    - [x] Small (trivial changes, such as build error)

## PR Overview

While `afl::option::GetHavocStackPow2<aflplusplus::option::AFLplusplusTag>` is overridden in https://github.com/fuzzuf/fuzzuf/pull/99, actually it's not used :(

https://github.com/fuzzuf/fuzzuf/blob/6c930ad141f1e9fcfe281e1c48a10fd37229cc74/algorithms/afl_common/afl_havoc_optimizer.cpp#L41
https://github.com/fuzzuf/fuzzuf/blob/6c930ad141f1e9fcfe281e1c48a10fd37229cc74/include/fuzzuf/cli/fuzzer/aflplusplus/build_aflplusplus_fuzzer_from_args.hpp#L290

## Concerns (Optional)

I have one thing to discuss (there is no need to deal with it in this PR though).
This kind of bug (something, that we thought was used, is actually not used) is common to fuzzuf (e.g., this one, or https://github.com/fuzzuf/fuzzuf/pull/72).
This means that we should have a countermeasure for this if possible, and probably that tests are not enough.
Any idea for the measures? At least I think we should dump these configure values to a log so that we can get aware of it being unchanged.

- [ ] Performance
- [ ] Source Code Quality

---

> The PR author should fill in the following checklist when submitting this PR.

#### Optional Entries
- [ ] If this PR is a PR type A/B-1, there is a cross-link between this PR and the related issue.

#### Mandatory Entries
- [ ] The PR title is a summary of the changes.
- [ ] Completed each required field of the PR.

---
> The PR author should fill out the following checklist in the comments to confirm that this PR is ready to be merged

- [ ] CI is green or confirmed test run results.
- [ ] All change suggestions from reviewers have been resolved (fixed or foregone).

---
> The maintainer of this repository will set up a reviewer for each PR.
> PR reviewers should review this PR in terms of the checklist below before moving on to a detailed code review. Please comment on their initial response by filling in the checklist below.

#### Optional Entries
- [ ] The reviewer assigned more reviewers if needed.
- [ ] The reviewer noted that it is necessary to break out some of the changes in this PR into other PRs if needed.
- [ ] The reviewer noted that the initial response is insufficient if needed.

#### Mandatory Entries
- [ ] The title of this PR summarizes the changes made by this PR properly.
- [ ] The target branch of this PR is as intended.
- [ ] The reviewer understands the issues in this PR.
- [ ] The reviewer plans to review with an appropriate workload based on the importance of this PR.

---
> When the PR reviewer concludes that this PR is ready to be merged, please fill in the checklist below by posting it in the comment. If there is more than one reviewer, please do this on your own.

#### Optional Entries
- [ ] The reviewer noted that if you believe that new tests are needed to evaluate this PR, they have been noted.
- [ ] If minor refactorings are not mentioned in the PR, I understand the intent.
- [ ] If this PR is a PR type A/B-1, we have agreed on this PR's design, direction, and granularity in the related issue.

#### Mandatory Entries
- [ ] The reviewer understands how this PR addresses the issue and the specific changes.
- [ ] This PR uses the best possible issue resolution that the reviewer can think of.
- [ ] This PR is ready to be merged.

### CODE REVIEW

**Comment by potetisensei** [comment]
run tests

**Review by arata-nvm — APPROVED** [review]
LGTM

**Comment by arata-nvm** [comment]
> Any idea for the measures? At least I think we should dump these configure values to a log so that we can get aware of it being unchanged.

I agree to dump the configure values. Also, adding unit tests would probably prevent this issue.

**Comment by potetisensei** [comment]
> Also, adding unit tests would probably prevent this issue.

The problem is that it is somewhat difficult to add unit tests for `HierarFlowRoutine` because it tends to depend on other routines. But it's just a kind of excuse and writing unit tests is still possible. So we need to try to do that.

**Pull request merged**
